baseURL: https://www.manuel-rademaker.com/
theme: hugo-apero
languageCode: en
title: Manuel Rademaker - Personal Website
author: Manuel Rademaker
copyright: ''
googleAnalytics: G-HBK6VVSS3Z
metaDataFormat: yaml
footnoteReturnLinkContents: '&#8617;'
paginate: 5
preserveTaxonomyNames: yes
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - \.knit\.md$
  - \.utf8\.md$
  - _cache$
  - _temp$
  - _ignore$
  - code$
enableEmoji: true
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      hardwraps: no
      unsafe: yes
  highlight:
    style: github
  tableOfContents:
    endLevel: 2
    ordered: no
    startLevel: 2
params: 
  author: Manuel Rademaker
  # These are the parameters used in hugo the hugo theme. You can name theme
  # however you like, but renaming existing ones break the site as you need
  # to update the reference in the theme too.
  custom_theme: ''
  # serif options: Fraunces / EB Garamond / Bitter
  # sans-serif options: Commissioner / Alegreya Sans / Metropolis
  customheadingFontFamily: Fraunces
  customtextFontFamily: Commissioner
  headingFontFamily: sans-serif
  textFontFamily: sans-serif
  description: My personal homepage, blog, and project portfolio
  favicon: /iris-flower-favicon.ico
  logo: /iris-flower.png
  mainSections:
    - about
    - blog
    - project
    - cv
  navallcaps: yes
  sharing_image: /Me.jpg
  social:
    - icon: github
      icon_pack: fab
      url: https://github.com/M-E-Rademaker
    - icon: linkedin
      icon_pack: fab
      url: https://www.linkedin.com/in/manuel-rademaker/
    - icon: xing
      icon_pack: fab
      url: https://www.xing.com/profile/Manuel_Rademaker3/cv
    - icon: researchgate
      icon_pack: ai
      url: https://www.researchgate.net/profile/Manuel-Rademaker
    - icon: stack-overflow
      icon_pack: fab
      url: https://stackoverflow.com/users/4046004/manuel-r
    - icon: envelope
      icon_pack: fas
      url: /contact/
  socialInFooter: yes
  socialInHeader: no
  # one of: forest / grayscale / peach / plum /
  #         poppy / sky / violet / water 
  theme: sky
  utterances:
    issue_term: pathname
    label: 'comments :crystal_ball:'
    repo_name: M-E-Rademaker/personal-website
    theme: boxy-light
    use_utterances: false
taxonomies:
  category: categories
  series: series
  tag: tags
menu:
  footer:
    - name: License
      title: License
      url: /license/
      weight: 1
    - name: Contact
      title: Contact form
      url: /contact/
      weight: 2
  header:
    - name: About Me
      title: About Me
      url: /about/
      weight: 1
    - name: Blog
      title: Blog
      url: /blog/
      weight: 2
    - name: Projects
      title: Project Portfolio
      url: /project/
      weight: 3
    - name: CV
      title: CV
      url: /cv/cv.pdf
      weight: 4
privacy:
  googleAnalytics:
    anonymizeIP: yes
    disable: no
    respectDoNotTrack: yes